set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property PACKAGE_PIN J14 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk]

set_property PACKAGE_PIN H16 [get_ports {mdio_mdc          }]
set_property PACKAGE_PIN H13 [get_ports {mdio_mdio_io      }]
set_property PACKAGE_PIN H12 [get_ports {phy_rst_n         }]
set_property PACKAGE_PIN G14 [get_ports {rgmii_rxc         }]
set_property PACKAGE_PIN E13 [get_ports {rgmii_rx_ctl      }]
set_property PACKAGE_PIN F13 [get_ports {rgmii_rd[0]       }]
set_property PACKAGE_PIN F12 [get_ports {rgmii_rd[1]       }]
set_property PACKAGE_PIN E12 [get_ports {rgmii_rd[2]       }]
set_property PACKAGE_PIN G11 [get_ports {rgmii_rd[3]       }]
set_property PACKAGE_PIN D11 [get_ports {rgmii_txc         }]
set_property PACKAGE_PIN E11 [get_ports {rgmii_tx_ctl      }]
set_property PACKAGE_PIN F10 [get_ports {rgmii_td[0]       }]
set_property PACKAGE_PIN G10 [get_ports {rgmii_td[1]       }]
set_property PACKAGE_PIN D10 [get_ports {rgmii_td[2]       }]
set_property PACKAGE_PIN E10 [get_ports {rgmii_td[3]       }]

set_property IOSTANDARD LVCMOS18 [get_ports {mdio_mdc          }]
set_property IOSTANDARD LVCMOS18 [get_ports {mdio_mdio_io      }]
set_property IOSTANDARD LVCMOS18 [get_ports {phy_rst_n         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxc         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rx_ctl      }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[0]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[1]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[2]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[3]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txc         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_tx_ctl      }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[0]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[1]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[2]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[3]       }]